// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.0
// source: idl/rank/rank.proto

package rank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Rank_GetUserRank_FullMethodName     = "/rank.Rank/GetUserRank"
	Rank_GetLowRankList_FullMethodName  = "/rank.Rank/GetLowRankList"
	Rank_GetHighRankList_FullMethodName = "/rank.Rank/GetHighRankList"
)

// RankClient is the client API for Rank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankClient interface {
	GetUserRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankItem, error)
	GetLowRankList(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankList, error)
	GetHighRankList(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankList, error)
}

type rankClient struct {
	cc grpc.ClientConnInterface
}

func NewRankClient(cc grpc.ClientConnInterface) RankClient {
	return &rankClient{cc}
}

func (c *rankClient) GetUserRank(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankItem, error) {
	out := new(RankItem)
	err := c.cc.Invoke(ctx, Rank_GetUserRank_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankClient) GetLowRankList(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankList, error) {
	out := new(RankList)
	err := c.cc.Invoke(ctx, Rank_GetLowRankList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankClient) GetHighRankList(ctx context.Context, in *GetRankRequest, opts ...grpc.CallOption) (*RankList, error) {
	out := new(RankList)
	err := c.cc.Invoke(ctx, Rank_GetHighRankList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServer is the server API for Rank service.
// All implementations must embed UnimplementedRankServer
// for forward compatibility
type RankServer interface {
	GetUserRank(context.Context, *GetRankRequest) (*RankItem, error)
	GetLowRankList(context.Context, *GetRankRequest) (*RankList, error)
	GetHighRankList(context.Context, *GetRankRequest) (*RankList, error)
	mustEmbedUnimplementedRankServer()
}

// UnimplementedRankServer must be embedded to have forward compatible implementations.
type UnimplementedRankServer struct {
}

func (UnimplementedRankServer) GetUserRank(context.Context, *GetRankRequest) (*RankItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRank not implemented")
}
func (UnimplementedRankServer) GetLowRankList(context.Context, *GetRankRequest) (*RankList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLowRankList not implemented")
}
func (UnimplementedRankServer) GetHighRankList(context.Context, *GetRankRequest) (*RankList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighRankList not implemented")
}
func (UnimplementedRankServer) mustEmbedUnimplementedRankServer() {}

// UnsafeRankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankServer will
// result in compilation errors.
type UnsafeRankServer interface {
	mustEmbedUnimplementedRankServer()
}

func RegisterRankServer(s grpc.ServiceRegistrar, srv RankServer) {
	s.RegisterService(&Rank_ServiceDesc, srv)
}

func _Rank_GetUserRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).GetUserRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rank_GetUserRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).GetUserRank(ctx, req.(*GetRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rank_GetLowRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).GetLowRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rank_GetLowRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).GetLowRankList(ctx, req.(*GetRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rank_GetHighRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServer).GetHighRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rank_GetHighRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServer).GetHighRankList(ctx, req.(*GetRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rank_ServiceDesc is the grpc.ServiceDesc for Rank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rank.Rank",
	HandlerType: (*RankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserRank",
			Handler:    _Rank_GetUserRank_Handler,
		},
		{
			MethodName: "GetLowRankList",
			Handler:    _Rank_GetLowRankList_Handler,
		},
		{
			MethodName: "GetHighRankList",
			Handler:    _Rank_GetHighRankList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/rank/rank.proto",
}
